version: '3'
services: 
  postgres: 
    image: nanlist/postgres12.3:v1
    restart: always
    container_name: sonarqube_postgres
    ports:
      - 5432:5432
    volumes:
      # 设置与宿主机时间同步
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai    
      POSTGRES_USER: sonar   
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks: 
      - sonar-network
  sonar:
    image: nanlist/sonarqube7.8-community:v1
    restart: always 
    container_name: sonarqube
    depends_on:
      - postgres
    volumes:
      # 设置与宿主机时间同步
      - /etc/localtime:/etc/localtime:ro      
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
    networks: 
      - sonar-network
networks:
  sonar-network:
    driver: bridge
