version: '3.1'
services:
  dubbo-admin:
    restart: always
    image: sunchaserlilu/dubbo-admin:2021.0.0
    container_name: dubbo-admin
    ports:
      - 6001:8080
    environment:
      - admin.config-center=zookeeper://${ip}:${port}
      - admin.registry.address=zookeeper://${ip}:${port}
      - admin.metadata-report.address=zookeeper://${ip}:${port}
      - admin.root.user.name=root
      - admin.root.user.password=root